-- Demo bakery used for click-through testing. Already applied to the project database.
-- The demo owner and driver accounts were created in auth.users with a password shared in the project thread.
-- To remove the demo later:
--   delete from public.businesses where name_en like '%(demo)';
--   delete from auth.users where email like '%@m3akorder.test';
